[Settings]
ID = "adoring-keller-d162f4"

[build]
base = "client"
publish = "client/dist"
command = "npm run generate"

[context.production]
environment = { API_URL = "https://orangebear.enginehost.com" }